### PR TITLE
feat: new search component - implement Combobox approach

### PR DESCRIPTION
**Pull request by MengLinMaker**
## Addresses:
- #504
- #224 - command palette can also be implemented with combobox
- #262 - filter would be managed externally instead of internally
- #261

## Draft `Search` component implementation using Combobox underneath

This solution should be more maintainable than #501

- [x] Component
  - [x] Export some `Combobox` components as `Search`
  - [x] `SearchRoot` to implement `ComboBoxBase` disabling defaultFilter as this is handled externally - eg: database
  - [x] Add suggestion debouncer
  - [x] Indicator for loading search query
  - [x] No results found?
  - [x] Remove extraneous components?

- [x] Test
  - [ ] ~~No results - cannot open dropdown with solid testing library~~
  - [x] Debouncer

- [x] Doc
  - [x] Import, Features, Anatomy
  - [x] Example: Emoji search
  - [x] Usage: Debounce
  - [x] Usage: Cmdk style
  - [ ] Usage: Chip query search?
  - [x] API Reference
  - [x] Rendered elements, Accessibility

- [x] Bugs:
  - [x] **The dropdown bug:** empty `options` -> typing -> non-empty `options` -> results in no dropdown unless dropdown is already open (Nani? ¯\_(ツ)_/¯)
  - [x] Selecting item triggers onInputChange, which should not trigger
  - [x] Resets input on blur, which it shouldn't - add `noResetInputOnBlur` option to Combobox
  - [ ] ~~Old dropdown options shown on blur - this is a combobox behaviour. WHY?~~
  
Note: I'm using `minisearch` npm package to perform text search

## For the most part, this component is considered complete

### CODE REVIEW

**Comment by MengLinMaker** [comment]
Example search:
https://github.com/user-attachments/assets/98b2abe6-ad67-4c1d-bb61-2e4c57829a56

**Comment by MengLinMaker** [comment]
Typing fast then stopping somehow does not display suggestion options:

https://github.com/user-attachments/assets/d8575d9a-1e63-4fa0-92ce-541c346f1b23

Issue seems to occur when `debounceOptionsMillisecond` is over 100ms

**Comment by MengLinMaker** [comment]
# The dropdown bug - solution

Found the cause of the bug:
- The bug originates from `Combobox.Input` `onInput` function, which controls when to open the dropdown.
- When `options` is empty, so `collection().getSize()` = 0, `context.open` is not triggered.

The possible fix:
- `allowsEmptyCollection` should allow `Combobox.Input` `onInput` function to trigger `context.open`
- Internally `context.open`  will open the dropdown when `allowsEmptyCollection` is set to true

**Comment by MengLinMaker** [comment]
@jer3m01 I think this component is ready for review

**Comment by MengLinMaker** [comment]
Fixed some dark mode styling issues:
https://deploy-preview-506--kobalte.netlify.app/docs/core/components/search/#cmdk-style

**Review by jer3m01 — APPROVED** [review]
Thanks for all the work! Looks great!

Could you open separate issues for the bugs that are still present?

Will merge soon.

**Pull request merged**
