### PR TITLE
feat: color components

### PR DESCRIPTION
**Pull request by HBS999**
This PR adds 4 new color components: ColorArea, ColorSlider, ColorChannelField and ColorSwatch.

### CODE REVIEW

**Review by jer3m01 — CHANGES_REQUESTED** [review]
Thanks for the PR, looks amazing!

Two small issues with the `ColorArea`; clicking the circle and dragging works correctly but clicking on a color doesn't seem to calculate the position correctly and moves to the top right corner. Video demo:

https://github.com/user-attachments/assets/7f1f0c21-fb5d-4fd9-90e9-b0e94df455a4

Second issue (`ColorArea` also); there's no aria label for the currently selected color. This is correctly set for the `ColorSwatch` and `ColorSlider` but missing in `ColorArea`.

Other than that the PR is ready to go, really good job on extending the existing components for these!
(Make sure to also pass CI).

Thanks!

**Comment by HBS999** [comment]
The ColorArea works flawlessly in the playground but breaks in the docs. I was hoping this was an issue with the dev build of the docs and it will be fixed in prod. However look like the netlify bot doesn’t create deploy links to test so I am kinda lost here. Will look more into it now.

**Comment by HBS999** [comment]
Hi Jeremy, 

I fixed the ColorArea issue and I have also added default aria-label for the hidden inputs.

> Second issue (ColorArea also); there's no aria label for the currently selected color. This is correctly set for the ColorSwatch and ColorSlider but missing in ColorArea.

Do you mean an aria-label on the thumb with the current value?

**Comment by jer3m01** [comment]
> Do you mean an aria-label on the thumb with the current value?

Yeah I think it that would make it a lot nice to interact with, I'd put the label on the entire color area rather than just the thumb.

**Comment by HBS999** [comment]
I’ve put it on the thumb instead. Since the ColorArea is neither interactive nor a landmark, I believe it will be ignored unless I am misunderstanding how aria-label works. Let me know what you think.

**Comment by jer3m01** [comment]
> I’ve put it on the thumb instead. Since the ColorArea is neither interactive nor a landmark, I believe it will be ignored unless I am misunderstanding how aria-label works. Let me know what you think.

I think you're right, the label on the thumb is more precise. Label on the color area would read incorrectly as a color swatch.

**Comment by HBS999** [comment]
Hmm I don’t understand why CI is failing

**Review by jer3m01 — APPROVED** [review]
Looks all good! Thanks for the PR!

Will merge soon.

**Pull request merged**
