### PR TITLE
import file extensions

### PR DESCRIPTION
**Pull request by sachaw**
Fix for #190

### CODE REVIEW

**Comment by sachaw** [comment]
@fabien-ml Just wondering if you could please review this, thanks.

**Comment by fabien-ml** [comment]
Hi thanks for the PR.

Module resolution is a bit out of my knowledge. Does this work when using vite or solid-start ?

**Comment by sachaw** [comment]
Yes it has no impact on backwards compatibility. CJ's allows imports with or without file extensions, esm (as per the spec) mandates them.
I'm currently using this with Vite.

**Comment by milesj** [comment]
Just going to chime in here that this PR feels... odd. Why add the extensions to the source files and not have the bundle/transpile process add them? This can easily be done with rollup.

**Comment by fabien-ml** [comment]
I haven't follow this module resolution/typescript 5 story and honestly doesn't have time to, sorry. Adding file extension manually will be a pain for me to work with day to day. Also I don't know if this will cause problems when using `solid-start`. 
So I'm not gonna merge this PR for now, if someone has another solution involving rollup feel free to open a PR.
Thanks you anyway for your time @sachaw

**Comment by sachaw** [comment]
@milesj I agree that it would seem most elegant to have your bundler handle things like this, however as this is a change that is in the ESM spec, it is going to be slowly streamlined across the various JavaScript tools (including typescript).
You can get your ide to automatically add file extensions to imports, also linters & formatters can also help here.
If you also update your typescripts module resolution option, tax will also enforce this (it will likely become default at some point).

I'll likely open another pr that adds the appropriate linting rules.

**Comment by sachaw** [comment]
@fabien-ml Just did some further research as I was looking to see if this could be handled by rollup.
Turns out it cant (as far as I can see) as both the .js files and .d.ts files should contain file extensions in there import statements.

As for solid start, it works, I tried it out today. Also take a look at the solid/solid start source code, they are using import file extensions.

This will in no way break backwards comparability, as it stands now, this package is unable to be used in any projects using modern module resolution. This project has already set `type: "module"` in the `package.json` this is the other step required to support ESM (excellent write up here: https://www.typescriptlang.org/docs/handbook/esm-node.html)

I'll open another PR if you'll accept it, Ideally an added change in the tsconfig file for the core module setting the moduleResolution to something newer, will enforce compliance without breaking anything,

**Pull request closed without merging**
