### PR TITLE
fix: new esm imports

### PR DESCRIPTION
**Pull request by sachaw**

### CODE REVIEW

**Comment by fabien-ml** [comment]
Hi, can you pull the latest changes from `main` ?

**Comment by sachaw** [comment]
@fabien-ml This should now be working, docs and playground compile without any changes so this change should not require any changes for users.
vite enforces `.jsx` files to be imported as such `.js` won't work.
If your using vscode, auto imports will do this for you.

I'd squashing this as the merge strategy as there's a fair few line changes in the history that aren't needed.

If there's any issues that arise (I don't expect any) please tag me and I'll investigate/fix
Thanks.

**Comment by sachaw** [comment]
I'd also recommending updating your version of pnpm as they have moved to version 6 of there lockfile specification.

**Comment by fabien-ml** [comment]
@sachaw there is something wrong with the test suite.

**Comment by sachaw** [comment]
Ok, I'll look into it

**Comment by fabien-ml** [comment]
> Ok, I'll look into it

Sorry for the late response, have you find what's the problem with tests ?

**Comment by fabien-ml** [comment]
I'm closing it for now since i'm not able to make it work.

**Pull request closed without merging**
