### PR TITLE
feat: PinInput component

### PR DESCRIPTION
**Pull request by HBS999**
This PR adds a new PinInput component.

### CODE REVIEW

**Comment by jer3m01** [comment]
Hey thanks for the PR, however PinInput already exists in corvu and I'm not currently interested in maintaining one in Kobalte.

**Comment by HBS999** [comment]
Hi, it is not the same. The one in Corvu is a simple OTP one. This one has more functionality, including different input modes (alphabetic, alphanumeric) and the fact that you can supply your own pattern.

**Comment by GiyoMoon** [comment]
Hey, the corvu OTP Field has all the features that you mentioned. Different input modes and patterns can be configured with the `pattern` property on the `<OtpField.Input />` component and masking inputs is easy as the slots are just visual component and it's up to the user to style them and whether they want to show the values or mask them.

**Comment by HBS999** [comment]
Hi Jasmin, nice seeing you here! It’s my fault for skimming the docs quickly 🤦‍♂️! I apologize.

**Pull request closed without merging**
